name: dbt_sales_analytics
version: '1.0.0'
config-version: 2

profile: dbt_sales_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["data/raw"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_sales_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
